build:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - apk add nodejs yarn git make
  script:
    - make deploy
  artifacts:
    paths:
      - dist
  cache:
    key: node_modules
    paths:
      - node_modules/
      - .yarn/
